### ISSUE TITLE
unable to find python binary

### ISSUE THREAD

**Issue by wesbos** [wakatime/sublime-wakatime#21] opened 2014-01-29 22:44 UTC
I havent a student on Windows and Wakatime isn't logging any any time. He is getting the error "unable to find python binary". Any idea what this is?

**Comment by scottx** [comment] 2015-03-09 21:07
Hi,
I googled but couldn't find any help.
After installing Python, shouldn't we need to specify on Sublime Text the path to Python binaries?
How can I do that?
Thank you!

**Comment by alanhamlett** [comment] 2015-03-09 22:30
The plugin should detect python if it's installed to the default location, or in your PATH variable.

**Comment by scottx** [comment] 2015-03-09 22:58
Thank you Alan, I had Python for x64 installed, but my Sublime Text runs as a 32bit application, perhaps that was my problem. I uninstalled Python and after installing the version for x86, Sublime Text started running Wakatime.

**Comment by alanhamlett** [comment] 2015-03-10 02:07
Ok, I'll make note of this to look into. Glad it's working now.

**Comment by fabiobiondi** [comment] 2015-03-31 10:53
Same problem here on Win8.1 x64 . 
There is no differences between Python 64bit or 32bit because the plugin still doesn't work :(

**Comment by alanhamlett** [comment] 2015-03-31 20:26
@fabiobiondi When you (and your student @wesbos) open a cmd prompt and type `which python` and `python --version` what output do you see?

**Comment by fabiobiondi** [comment] 2015-03-31 20:45
Hi Alan, I solved my problem right now using "which python". 
I didn't remember there was another Python version on my PC and in my environment variables added by the Blackberry SDK for Cordova. So the newest Python installation didn't exist for my OS ; )

Now Wakatime seems to work. Great work dude and thanks for support  : )

**Comment by alanhamlett** [comment] 2015-03-31 22:42
Nice, glad you figured out the cause. I'll close this issue now.

**Closed by alanhamlett** 2015-03-31 22:42 UTC
